project:
  type: website
  output-dir: docs

website:
  title: "NB Quarto Blog"
  description: "A blog about programming, and technology"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/watanabe3tipapa
        aria-label: GitHub
  search: true
  page-footer: 
    center: "© 2024 watanabe3tipapa. Built with [Quarto](https://quarto.org/)"
  repo-url: "https://github.com/watanabe3tipapa/nb-quarto-blog"
  repo-actions: [edit, issue]
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap

metadata-files: [_metadata.yml]

editor: visual

